// /src/features/recipeEditor/manual_texture_map.ts

/**
 * A manually curated map to override or correct texture lookups for items where the
 * identifier is DIFFERENT from its corresponding texture filename.
 * This has the highest priority.
 *
 * Key: The item's short name (e.g., "wooden_sword").
 * Value: The texture's short name (e.g., "wood_sword").
 */
 export const manualTextureMap = new Map<string, string>([
    // Name variants (e.g. wooden vs wood, golden vs gold)
    ['wooden_sword', 'wood_sword'],
    ['wooden_axe', 'wood_axe'],
    ['wooden_pickaxe', 'wood_pickaxe'],
    ['wooden_shovel', 'wood_shovel'],
    ['wooden_hoe', 'wood_hoe'],
    ['golden_sword', 'gold_sword'],
    ['golden_axe', 'gold_axe'],
    ['golden_pickaxe', 'gold_pickaxe'],
    ['golden_shovel', 'gold_shovel'],
    ['golden_hoe', 'gold_hoe'],
    ['golden_helmet', 'gold_helmet'],
    ['golden_chestplate', 'gold_chestplate'],
    ['golden_leggings', 'gold_leggings'],
    ['golden_boots', 'gold_boots'],
    ['golden_horse_armor', 'gold_horse_armor'],
    ['golden_apple', 'apple_golden'],
    ['enchanted_golden_apple', 'apple_golden'],

    // Food items with different naming conventions
    ['beef', 'beef_raw'],
    ['cooked_beef', 'beef_cooked'],
    ['porkchop', 'porkchop_raw'],
    ['cooked_porkchop', 'porkchop_cooked'],
    ['chicken', 'chicken_raw'],
    ['cooked_chicken', 'chicken_cooked'],
    ['mutton', 'mutton_raw'],
    ['cooked_mutton', 'mutton_cooked'],
    ['rabbit', 'rabbit_raw'],
    ['cooked_rabbit', 'rabbit_cooked'],
    ['cod', 'fish_raw'],
    ['cooked_cod', 'fish_cooked'],
    ['salmon', 'fish_salmon_raw'],
    ['cooked_salmon', 'fish_salmon_cooked'],
    ['pufferfish', 'fish_pufferfish_raw'],
    ['tropical_fish', 'fish_clownfish_raw'],
    ['melon_slice', 'melon'],
    ['glistering_melon_slice', 'melon_speckled'],

    // Seeds
    ['wheat_seeds', 'seeds_wheat'],
    ['pumpkin_seeds', 'seeds_pumpkin'],
    ['melon_seeds', 'seeds_melon'],
    ['beetroot_seeds', 'seeds_beetroot'],

    // Renamed items
    ['sugar_cane', 'reeds'],
    ['totem_of_undying', 'totem'],
    ['turtle_scute', 'turtle_shell_piece'],
    ['fire_charge', 'fireball'],
    ['popped_chorus_fruit', 'chorus_fruit_popped'],
    ['nether_wart', 'nether_wart'], // Item is nether_wart, texture is nether_wart
    ['netherbrick', 'netherbrick'],

    // Tools and complex items
    ['writable_book', 'book_writable'],
    ['written_book', 'book_written'],
    ['enchanted_book', 'book_enchanted'],
    ['book', 'book_normal'],
    ['frame', 'item_frame'],
    ['glow_frame', 'glow_item_frame'],
    ['clock', 'clock_item'],
    ['compass', 'compass_item'],
    ['lodestone_compass', 'lodestonecompass_item'],
    ['recovery_compass', 'recovery_compass_item'],
    ['filled_map', 'map_filled'],
    ['empty_map', 'map_empty'],
    
    // Potions
    ['potion', 'potion_bottle_drinkable'],
    ['splash_potion', 'potion_bottle_splash'],
    ['lingering_potion', 'potion_bottle_lingering'],

    // Music Discs (record_*)
    ['music_disc_11', 'record_11'],
    ['music_disc_13', 'record_13'],
    ['music_disc_5', 'record_5'],
    ['music_disc_blocks', 'record_blocks'],
    ['music_disc_cat', 'record_cat'],
    ['music_disc_chirp', 'record_chirp'],
    ['music_disc_far', 'record_far'],
    ['music_disc_mall', 'record_mall'],
    ['music_disc_mellohi', 'record_mellohi'],
    ['music_disc_otherside', 'record_otherside'],
    ['music_disc_pigstep', 'record_pigstep'],
    ['music_disc_stal', 'record_stal'],
    ['music_disc_strad', 'record_strad'],
    ['music_disc_wait', 'record_wait'],
    ['music_disc_ward', 'record_ward'],
    ['music_disc_relic', 'music_disc_relic'], // Direct match but good for consistency

    // Boats
    ['oak_boat', 'boat_oak'],
    ['spruce_boat', 'boat_spruce'],
    ['birch_boat', 'boat_birch'],
    ['jungle_boat', 'boat_jungle'],
    ['acacia_boat', 'boat_acacia'],
    ['dark_oak_boat', 'boat_dark_oak'],

    // Signs
    ['oak_sign', 'sign'],
    ['spruce_sign', 'sign_spruce'],
    ['birch_sign', 'sign_birch'],
    ['jungle_sign', 'sign_jungle'],
    ['acacia_sign', 'sign_acacia'],
    ['dark_oak_sign', 'sign_darkoak'],
    ['crimson_sign', 'sign_crimson'],
    ['warped_sign', 'sign_warped'],
    ['mangrove_sign', 'mangrove_sign'],
    ['cherry_sign', 'cherry_sign'],
    ['bamboo_sign', 'bamboo_sign'],
    ['pale_oak_sign', 'pale_oak_sign'],
    
    // Hanging Signs
    ['oak_hanging_sign', 'oak_hanging_sign'],
    ['spruce_hanging_sign', 'spruce_hanging_sign'],
    ['birch_hanging_sign', 'birch_hanging_sign'],
    ['jungle_hanging_sign', 'jungle_hanging_sign'],
    ['acacia_hanging_sign', 'acacia_hanging_sign'],
    ['dark_oak_hanging_sign', 'dark_oak_hanging_sign'],
    ['crimson_hanging_sign', 'crimson_hanging_sign'],
    ['warped_hanging_sign', 'warped_hanging_sign'],
    ['mangrove_hanging_sign', 'mangrove_hanging_sign'],
    ['cherry_hanging_sign', 'cherry_hanging_sign'],
    ['bamboo_hanging_sign', 'bamboo_hanging_sign'],
    ['pale_oak_hanging_sign', 'pale_oak_hanging_sign'],

    // Doors (as items)
    ['wooden_door', 'door_wood'],
    ['spruce_door', 'door_spruce'],
    ['birch_door', 'door_birch'],
    ['jungle_door', 'door_jungle'],
    ['acacia_door', 'door_acacia'],
    ['dark_oak_door', 'door_dark_oak'],

    // Colored Blocks (mapping base name to a default color or specific texture name)
    ['bed', 'bed_red'],
    ['banner', 'banner_pattern'], // No simple default banner, mapping to pattern
    ['undyed_shulker_box', 'shulker_top_undyed'],
    ['black_shulker_box', 'shulker_top_black'],
    ['blue_shulker_box', 'shulker_top_blue'],
    ['brown_shulker_box', 'shulker_top_brown'],
    ['cyan_shulker_box', 'shulker_top_cyan'],
    ['gray_shulker_box', 'shulker_top_gray'],
    ['green_shulker_box', 'shulker_top_green'],
    ['light_blue_shulker_box', 'shulker_top_light_blue'],
    ['lime_shulker_box', 'shulker_top_lime'],
    ['magenta_shulker_box', 'shulker_top_magenta'],
    ['orange_shulker_box', 'shulker_top_orange'],
    ['pink_shulker_box', 'shulker_top_pink'],
    ['purple_shulker_box', 'shulker_top_purple'],
    ['red_shulker_box', 'shulker_top_red'],
    ['light_gray_shulker_box', 'shulker_top_silver'],
    ['white_shulker_box', 'shulker_top_white'],
    ['yellow_shulker_box', 'shulker_top_yellow'],

    ['black_wool', 'wool_colored_black'],
    ['blue_wool', 'wool_colored_blue'],
    ['brown_wool', 'wool_colored_brown'],
    ['cyan_wool', 'wool_colored_cyan'],
    ['gray_wool', 'wool_colored_gray'],
    ['green_wool', 'wool_colored_green'],
    ['light_blue_wool', 'wool_colored_light_blue'],
    ['lime_wool', 'wool_colored_lime'],
    ['magenta_wool', 'wool_colored_magenta'],
    ['orange_wool', 'wool_colored_orange'],
    ['pink_wool', 'wool_colored_pink'],
    ['purple_wool', 'wool_colored_purple'],
    ['red_wool', 'wool_colored_red'],
    ['light_gray_wool', 'wool_colored_silver'],
    ['white_wool', 'wool_colored_white'],
    ['yellow_wool', 'wool_colored_yellow'],

    ['black_terracotta', 'hardened_clay_stained_black'],
    ['blue_terracotta', 'hardened_clay_stained_blue'],
    ['brown_terracotta', 'hardened_clay_stained_brown'],
    ['cyan_terracotta', 'hardened_clay_stained_cyan'],
    ['gray_terracotta', 'hardened_clay_stained_gray'],
    ['green_terracotta', 'hardened_clay_stained_green'],
    ['light_blue_terracotta', 'hardened_clay_stained_light_blue'],
    ['lime_terracotta', 'hardened_clay_stained_lime'],
    ['magenta_terracotta', 'hardened_clay_stained_magenta'],
    ['orange_terracotta', 'hardened_clay_stained_orange'],
    ['pink_terracotta', 'hardened_clay_stained_pink'],
    ['purple_terracotta', 'hardened_clay_stained_purple'],
    ['red_terracotta', 'hardened_clay_stained_red'],
    ['light_gray_terracotta', 'hardened_clay_stained_silver'],
    ['white_terracotta', 'hardened_clay_stained_white'],
    ['yellow_terracotta', 'hardened_clay_stained_yellow'],
    ['hardened_clay', 'hardened_clay'],

    ['black_stained_glass', 'glass_black'],
    ['blue_stained_glass', 'glass_blue'],
    ['brown_stained_glass', 'glass_brown'],
    ['cyan_stained_glass', 'glass_cyan'],
    ['gray_stained_glass', 'glass_gray'],
    ['green_stained_glass', 'glass_green'],
    ['light_blue_stained_glass', 'glass_light_blue'],
    ['lime_stained_glass', 'glass_lime'],
    ['magenta_stained_glass', 'glass_magenta'],
    ['orange_stained_glass', 'glass_orange'],
    ['pink_stained_glass', 'glass_pink'],
    ['purple_stained_glass', 'glass_purple'],
    ['red_stained_glass', 'glass_red'],
    ['light_gray_stained_glass', 'glass_silver'],
    ['white_stained_glass', 'glass_white'],
    ['yellow_stained_glass', 'glass_yellow'],
    
    ['black_stained_glass_pane', 'glass_pane_top_black'],
    ['blue_stained_glass_pane', 'glass_pane_top_blue'],
    ['brown_stained_glass_pane', 'glass_pane_top_brown'],
    ['cyan_stained_glass_pane', 'glass_pane_top_cyan'],
    ['gray_stained_glass_pane', 'glass_pane_top_gray'],
    ['green_stained_glass_pane', 'glass_pane_top_green'],
    ['light_blue_stained_glass_pane', 'glass_pane_top_light_blue'],
    ['lime_stained_glass_pane', 'glass_pane_top_lime'],
    ['magenta_stained_glass_pane', 'glass_pane_top_magenta'],
    ['orange_stained_glass_pane', 'glass_pane_top_orange'],
    ['pink_stained_glass_pane', 'glass_pane_top_pink'],
    ['purple_stained_glass_pane', 'glass_pane_top_purple'],
    ['red_stained_glass_pane', 'glass_pane_top_red'],
    ['light_gray_stained_glass_pane', 'glass_pane_top_silver'],
    ['white_stained_glass_pane', 'glass_pane_top_white'],
    ['yellow_stained_glass_pane', 'glass_pane_top_yellow'],

    // Candles (require path)
    ['candle', 'candles/candle'],
    ['white_candle', 'candles/white_candle'],
    ['orange_candle', 'candles/orange_candle'],
    ['magenta_candle', 'candles/magenta_candle'],
    ['light_blue_candle', 'candles/light_blue_candle'],
    ['yellow_candle', 'candles/yellow_candle'],
    ['lime_candle', 'candles/lime_candle'],
    ['pink_candle', 'candles/pink_candle'],
    ['gray_candle', 'candles/gray_candle'],
    ['light_gray_candle', 'candles/light_gray_candle'],
    ['cyan_candle', 'candles/cyan_candle'],
    ['purple_candle', 'candles/purple_candle'],
    ['blue_candle', 'candles/blue_candle'],
    ['brown_candle', 'candles/brown_candle'],
    ['green_candle', 'candles/green_candle'],
    ['red_candle', 'candles/red_candle'],
    ['black_candle', 'candles/black_candle'],
    
    // Harness (require path)
    ['white_harness', 'harness/harness_white'],
    ['orange_harness', 'harness/harness_orange'],
    ['magenta_harness', 'harness/harness_magenta'],
    ['light_blue_harness', 'harness/harness_light_blue'],
    ['yellow_harness', 'harness/harness_yellow'],
    ['lime_harness', 'harness/harness_lime'],
    ['pink_harness', 'harness/harness_pink'],
    ['gray_harness', 'harness/harness_gray'],
    ['light_gray_harness', 'harness/harness_light_gray'],
    ['cyan_harness', 'harness/harness_cyan'],
    ['purple_harness', 'harness/harness_purple'],
    ['blue_harness', 'harness/harness_blue'],
    ['brown_harness', 'harness/harness_brown'],
    ['green_harness', 'harness/harness_green'],
    ['red_harness', 'harness/harness_red'],
    ['black_harness', 'harness/harness_black'],
    
    // Spawn Eggs (require path and name change)
    ['zombie_pigman_spawn_egg', 'spawn_eggs/spawn_egg_zombified_piglin'],
    ['allay_spawn_egg', 'spawn_eggs/spawn_egg_allay'],
    ['axolotl_spawn_egg', 'spawn_eggs/spawn_egg_axolotl'],
    ['bat_spawn_egg', 'spawn_eggs/spawn_egg_bat'],
    ['bee_spawn_egg', 'spawn_eggs/spawn_egg_bee'],
    ['blaze_spawn_egg', 'spawn_eggs/spawn_egg_blaze'],
    ['cat_spawn_egg', 'spawn_eggs/spawn_egg_cat'],
    ['cave_spider_spawn_egg', 'spawn_eggs/spawn_egg_cave_spider'],
    ['chicken_spawn_egg', 'spawn_eggs/spawn_egg_chicken'],
    ['cod_spawn_egg', 'spawn_eggs/spawn_egg_cod'],
    ['cow_spawn_egg', 'spawn_eggs/spawn_egg_cow'],
    ['creeper_spawn_egg', 'spawn_eggs/spawn_egg_creeper'],
    ['dolphin_spawn_egg', 'spawn_eggs/spawn_egg_dolphin'],
    ['donkey_spawn_egg', 'spawn_eggs/spawn_egg_donkey'],
    ['drowned_spawn_egg', 'spawn_eggs/spawn_egg_drowned'],
    ['elder_guardian_spawn_egg', 'spawn_eggs/spawn_egg_elder_guardian'],
    ['ender_dragon_spawn_egg', 'spawn_eggs/spawn_egg_ender_dragon'],
    ['enderman_spawn_egg', 'spawn_eggs/spawn_egg_enderman'],
    ['endermite_spawn_egg', 'spawn_eggs/spawn_egg_endermite'],
    ['evoker_spawn_egg', 'spawn_eggs/spawn_egg_evoker'],
    ['fox_spawn_egg', 'spawn_eggs/spawn_egg_fox'],
    ['ghast_spawn_egg', 'spawn_eggs/spawn_egg_ghast'],
    ['glow_squid_spawn_egg', 'spawn_eggs/spawn_egg_glow_squid'],
    ['goat_spawn_egg', 'spawn_eggs/spawn_egg_goat'],
    ['guardian_spawn_egg', 'spawn_eggs/spawn_egg_guardian'],
    ['hoglin_spawn_egg', 'spawn_eggs/spawn_egg_hoglin'],
    ['horse_spawn_egg', 'spawn_eggs/spawn_egg_horse'],
    ['husk_spawn_egg', 'spawn_eggs/spawn_egg_husk'],
    ['iron_golem_spawn_egg', 'spawn_eggs/spawn_egg_iron_golem'],
    ['llama_spawn_egg', 'spawn_eggs/spawn_egg_llama'],
    ['magma_cube_spawn_egg', 'spawn_eggs/spawn_egg_magma_cube'],
    ['mooshroom_spawn_egg', 'spawn_eggs/spawn_egg_mooshroom'],
    ['mule_spawn_egg', 'spawn_eggs/spawn_egg_mule'],
    ['ocelot_spawn_egg', 'spawn_eggs/spawn_egg_ocelot'],
    ['panda_spawn_egg', 'spawn_eggs/spawn_egg_panda'],
    ['parrot_spawn_egg', 'spawn_eggs/spawn_egg_parrot'],
    ['phantom_spawn_egg', 'spawn_eggs/spawn_egg_phantom'],
    ['pig_spawn_egg', 'spawn_eggs/spawn_egg_pig'],
    ['piglin_spawn_egg', 'spawn_eggs/spawn_egg_piglin'],
    ['piglin_brute_spawn_egg', 'spawn_eggs/spawn_egg_piglin_brute'],
    ['pillager_spawn_egg', 'spawn_eggs/spawn_egg_pillager'],
    ['polar_bear_spawn_egg', 'spawn_eggs/spawn_egg_polar_bear'],
    ['pufferfish_spawn_egg', 'spawn_eggs/spawn_egg_pufferfish'],
    ['rabbit_spawn_egg', 'spawn_eggs/spawn_egg_rabbit'],
    ['ravager_spawn_egg', 'spawn_eggs/spawn_egg_ravager'],
    ['salmon_spawn_egg', 'spawn_eggs/spawn_egg_salmon'],
    ['sheep_spawn_egg', 'spawn_eggs/spawn_egg_sheep'],
    ['shulker_spawn_egg', 'spawn_eggs/spawn_egg_shulker'],
    ['silverfish_spawn_egg', 'spawn_eggs/spawn_egg_silverfish'],
    ['skeleton_spawn_egg', 'spawn_eggs/spawn_egg_skeleton'],
    ['skeleton_horse_spawn_egg', 'spawn_eggs/spawn_egg_skeleton_horse'],
    ['slime_spawn_egg', 'spawn_eggs/spawn_egg_slime'],
    ['snow_golem_spawn_egg', 'spawn_eggs/spawn_egg_snow_golem'],
    ['spider_spawn_egg', 'spawn_eggs/spawn_egg_spider'],
    ['squid_spawn_egg', 'spawn_eggs/spawn_egg_squid'],
    ['stray_spawn_egg', 'spawn_eggs/spawn_egg_stray'],
    ['strider_spawn_egg', 'spawn_eggs/spawn_egg_strider'],
    ['trader_llama_spawn_egg', 'spawn_eggs/spawn_egg_trader_llama'],
    ['tropical_fish_spawn_egg', 'spawn_eggs/spawn_egg_tropicalfish'],
    ['turtle_spawn_egg', 'spawn_eggs/spawn_egg_turtle'],
    ['vex_spawn_egg', 'spawn_eggs/spawn_egg_vex'],
    ['villager_spawn_egg', 'spawn_eggs/spawn_egg_villager'],
    ['vindicator_spawn_egg', 'spawn_eggs/spawn_egg_vindicator'],
    ['wandering_trader_spawn_egg', 'spawn_eggs/spawn_egg_wandering_trader'],
    ['witch_spawn_egg', 'spawn_eggs/spawn_egg_witch'],
    ['wither_spawn_egg', 'spawn_eggs/spawn_egg_wither'],
    ['wither_skeleton_spawn_egg', 'spawn_eggs/spawn_egg_wither_skeleton'],
    ['wolf_spawn_egg', 'spawn_eggs/spawn_egg_wolf'],
    ['zoglin_spawn_egg', 'spawn_eggs/spawn_egg_zoglin'],
    ['zombie_spawn_egg', 'spawn_eggs/spawn_egg_zombie'],
    ['zombie_horse_spawn_egg', 'spawn_eggs/spawn_egg_zombie_horse'],
    ['zombie_villager_spawn_egg', 'spawn_eggs/spawn_egg_zombie_villager'],
    ['frog_spawn_egg', 'spawn_eggs/spawn_egg_frog'],
    ['tadpole_spawn_egg', 'spawn_eggs/spawn_egg_tadpole'],
    ['warden_spawn_egg', 'spawn_eggs/spawn_egg_warden'],
    ['camel_spawn_egg', 'spawn_eggs/spawn_egg_camel'],
    ['sniffer_spawn_egg', 'spawn_eggs/spawn_egg_sniffer'],
    ['armadillo_spawn_egg', 'spawn_eggs/spawn_egg_armadillo'],
    ['bogged_spawn_egg', 'spawn_eggs/spawn_egg_bogged'],
    ['breeze_spawn_egg', 'spawn_eggs/spawn_egg_breeze'],
    ['creaking_spawn_egg', 'spawn_eggs/spawn_egg_creaking'],
    ['happy_ghast_spawn_egg', 'spawn_eggs/spawn_egg_happy_ghast'],
    
    // Block items that use a base texture for their inventory icon
    // Note: This is an interpretive mapping, as these items are 3D models.
    // The texture listed is the primary texture used for the model.
    ['oak_stairs', 'planks_oak'],
    ['spruce_stairs', 'planks_spruce'],
    ['birch_stairs', 'planks_birch'],
    ['jungle_stairs', 'planks_jungle'],
    ['acacia_stairs', 'planks_acacia'],
    ['dark_oak_stairs', 'planks_big_oak'],
    ['crimson_stairs', 'huge_fungus/crimson_planks'],
    ['warped_stairs', 'huge_fungus/warped_planks'],
    ['mangrove_stairs', 'mangrove_planks'],
    ['bamboo_stairs', 'bamboo_planks'],
    ['cherry_stairs', 'cherry_planks'],
    ['pale_oak_stairs', 'pale_oak_planks'],
    ['cobblestone_stairs', 'cobblestone'],
    ['stone_stairs', 'stone'],
    ['brick_stairs', 'brick'],
    ['stone_brick_stairs', 'stonebrick'],
    ['nether_brick_stairs', 'nether_brick'],
    ['sandstone_stairs', 'sandstone_top'],
    ['red_sandstone_stairs', 'red_sandstone_top'],
    ['quartz_stairs', 'quartz_block_top'],
    ['purpur_stairs', 'purpur_block'],
    ['prismarine_stairs', 'prismarine_rough'],
    ['prismarine_bricks_stairs', 'prismarine_bricks'],
    ['dark_prismarine_stairs', 'prismarine_dark'],
    
    ['oak_slab', 'planks_oak'],
    ['spruce_slab', 'planks_spruce'],
    ['birch_slab', 'planks_birch'],
    ['jungle_slab', 'planks_jungle'],
    ['acacia_slab', 'planks_acacia'],
    ['dark_oak_slab', 'planks_big_oak'],
    ['crimson_slab', 'huge_fungus/crimson_planks'],
    ['warped_slab', 'huge_fungus/warped_planks'],
    ['mangrove_slab', 'mangrove_planks'],
    ['bamboo_slab', 'bamboo_planks'],
    ['cherry_slab', 'cherry_planks'],
    ['pale_oak_slab', 'pale_oak_planks'],
    ['stone_slab', 'stone'],
    ['smooth_stone_slab', 'stone_slab_top'],
    ['sandstone_slab', 'sandstone_top'],
    ['cobblestone_slab', 'cobblestone'],
    ['brick_slab', 'brick'],
    ['stone_brick_slab', 'stonebrick'],
    ['nether_brick_slab', 'nether_brick'],
    ['quartz_slab', 'quartz_block_top'],
    
    ['oak_fence', 'planks_oak'],
    ['acacia_fence', 'planks_acacia'],
    ['dark_oak_fence', 'planks_big_oak'],
    ['spruce_fence', 'planks_spruce'],
    ['birch_fence', 'planks_birch'],
    ['jungle_fence', 'planks_jungle'],
    ['crimson_fence', 'huge_fungus/crimson_planks'],
    ['warped_fence', 'huge_fungus/warped_planks'],
    ['mangrove_fence', 'mangrove_planks'],
    ['bamboo_fence', 'bamboo_planks'],
    ['cherry_fence', 'cherry_planks'],
    ['pale_oak_fence', 'pale_oak_planks'],
    ['nether_brick_fence', 'nether_brick'],
    
    ['cobblestone_wall', 'cobblestone'],
    ['mossy_cobblestone_wall', 'cobblestone_mossy'],
    
    ['anvil', 'anvil_top_damaged_0'],
    ['chipped_anvil', 'anvil_top_damaged_1'],
    ['damaged_anvil', 'anvil_top_damaged_2'],

    ['waterlily', 'waterlily'],
    ['short_grass', 'tallgrass'], // Short grass item uses tallgrass texture
    ['fern', 'tallgrass'], // Fern item also often uses a generic plant texture placeholder in some contexts
    ['deadbush', 'deadbush'],
    ['tall_grass', 'double_plant_grass_carried'],
    ['large_fern', 'double_plant_fern_carried'],
    
    // Skulls/Heads - These are typically rendered blocks, mapping to a representative texture
    ['skeleton_skull', 'skull_pottery_sherd'], // Closest available texture in list for a skull
    ['wither_skeleton_skull', 'skull_pottery_sherd'],
    ['zombie_head', 'skull_pottery_sherd'],
    ['player_head', 'skull_pottery_sherd'],
    ['creeper_head', 'skull_pottery_sherd'],
    ['dragon_head', 'skull_pottery_sherd'],
    ['piglin_head', 'skull_pottery_sherd'],
]);